blacklist: []
build_space: build/reldebug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=RelWithDebInfo
- -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
- -DCMAKE_CXX_FLAGS=-fdiagnostics-color
devel_layout: linked
devel_space: devel/reldebug
extend_path: null
install: false
install_space: install/reldebug
isolate_install: false
jobs_args: []
log_space: logs/reldebug
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
