parameter_set:
    parameter_subset:
        float_override: 10.0
        float_array_override:
            - 1.0
            - 2.0
            - 3.0
    float_preserve: 20.0
    empty_array_override: []
