blacklist: []
build_space: build/debug
catkin_make_args: []
cmake_args:
- -DCMAKE_BUILD_TYPE=Debug
- -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
- -DCMAKE_CXX_FLAGS=-fdiagnostics-color
devel_layout: linked
devel_space: devel/debug
extend_path: null
install: false
install_space: install/debug
isolate_install: false
jobs_args: []
log_space: logs/debug
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
